/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 6
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_name = 1,
  anon_sym_is = 2,
  anon_sym_has = 3,
  anon_sym_must = 4,
  anon_sym_from = 5,
  anon_sym_to = 6,
  anon_sym_in = 7,
  anon_sym_outof = 8,
  anon_sym_at = 9,
  anon_sym_into = 10,
  anon_sym_upto = 11,
  anon_sym_downto = 12,
  sym_punctuation = 13,
  sym_source_file = 14,
  sym_keyword = 15,
  aux_sym_source_file_repeat1 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_name] = "name",
  [anon_sym_is] = "is",
  [anon_sym_has] = "has",
  [anon_sym_must] = "must",
  [anon_sym_from] = "from",
  [anon_sym_to] = "to",
  [anon_sym_in] = "in",
  [anon_sym_outof] = "outof",
  [anon_sym_at] = "at",
  [anon_sym_into] = "into",
  [anon_sym_upto] = "upto",
  [anon_sym_downto] = "downto",
  [sym_punctuation] = "punctuation",
  [sym_source_file] = "source_file",
  [sym_keyword] = "keyword",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_name] = sym_name,
  [anon_sym_is] = anon_sym_is,
  [anon_sym_has] = anon_sym_has,
  [anon_sym_must] = anon_sym_must,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_to] = anon_sym_to,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_outof] = anon_sym_outof,
  [anon_sym_at] = anon_sym_at,
  [anon_sym_into] = anon_sym_into,
  [anon_sym_upto] = anon_sym_upto,
  [anon_sym_downto] = anon_sym_downto,
  [sym_punctuation] = sym_punctuation,
  [sym_source_file] = sym_source_file,
  [sym_keyword] = sym_keyword,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_is] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_has] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_must] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_to] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_outof] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_at] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_into] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_upto] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_downto] = {
    .visible = true,
    .named = false,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '(' ||
          lookahead == ')' ||
          lookahead == ',' ||
          lookahead == '.' ||
          lookahead == ':' ||
          lookahead == ';') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 1:
      if (lookahead == '-') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_punctuation);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'd', 2,
        'f', 3,
        'h', 4,
        'i', 5,
        'm', 6,
        'o', 7,
        't', 8,
        'u', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(14);
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'p') ADVANCE(19);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_at);
      END_STATE();
    case 11:
      if (lookahead == 'w') ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_is);
      END_STATE();
    case 16:
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_to);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 21:
      if (lookahead == 'm') ADVANCE(28);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_has);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(29);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_into);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_must);
      END_STATE();
    case 31:
      if (lookahead == 'f') ADVANCE(34);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_upto);
      END_STATE();
    case 33:
      if (lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_outof);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_downto);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [anon_sym_is] = ACTIONS(1),
    [anon_sym_has] = ACTIONS(1),
    [anon_sym_must] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_to] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_outof] = ACTIONS(1),
    [anon_sym_at] = ACTIONS(1),
    [anon_sym_into] = ACTIONS(1),
    [anon_sym_upto] = ACTIONS(1),
    [anon_sym_downto] = ACTIONS(1),
    [sym_punctuation] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(5),
    [sym_keyword] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_name] = ACTIONS(5),
    [anon_sym_is] = ACTIONS(7),
    [anon_sym_has] = ACTIONS(7),
    [anon_sym_must] = ACTIONS(7),
    [anon_sym_from] = ACTIONS(7),
    [anon_sym_to] = ACTIONS(7),
    [anon_sym_in] = ACTIONS(7),
    [anon_sym_outof] = ACTIONS(7),
    [anon_sym_at] = ACTIONS(7),
    [anon_sym_into] = ACTIONS(7),
    [anon_sym_upto] = ACTIONS(7),
    [anon_sym_downto] = ACTIONS(7),
    [sym_punctuation] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_keyword] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_name] = ACTIONS(13),
    [anon_sym_is] = ACTIONS(7),
    [anon_sym_has] = ACTIONS(7),
    [anon_sym_must] = ACTIONS(7),
    [anon_sym_from] = ACTIONS(7),
    [anon_sym_to] = ACTIONS(7),
    [anon_sym_in] = ACTIONS(7),
    [anon_sym_outof] = ACTIONS(7),
    [anon_sym_at] = ACTIONS(7),
    [anon_sym_into] = ACTIONS(7),
    [anon_sym_upto] = ACTIONS(7),
    [anon_sym_downto] = ACTIONS(7),
    [sym_punctuation] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym_keyword] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_name] = ACTIONS(19),
    [anon_sym_is] = ACTIONS(22),
    [anon_sym_has] = ACTIONS(22),
    [anon_sym_must] = ACTIONS(22),
    [anon_sym_from] = ACTIONS(22),
    [anon_sym_to] = ACTIONS(22),
    [anon_sym_in] = ACTIONS(22),
    [anon_sym_outof] = ACTIONS(22),
    [anon_sym_at] = ACTIONS(22),
    [anon_sym_into] = ACTIONS(22),
    [anon_sym_upto] = ACTIONS(22),
    [anon_sym_downto] = ACTIONS(22),
    [sym_punctuation] = ACTIONS(25),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(28),
    [sym_name] = ACTIONS(30),
    [anon_sym_is] = ACTIONS(30),
    [anon_sym_has] = ACTIONS(30),
    [anon_sym_must] = ACTIONS(30),
    [anon_sym_from] = ACTIONS(30),
    [anon_sym_to] = ACTIONS(30),
    [anon_sym_in] = ACTIONS(30),
    [anon_sym_outof] = ACTIONS(30),
    [anon_sym_at] = ACTIONS(30),
    [anon_sym_into] = ACTIONS(30),
    [anon_sym_upto] = ACTIONS(30),
    [anon_sym_downto] = ACTIONS(30),
    [sym_punctuation] = ACTIONS(28),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_plo(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_name,
    .primary_state_ids = ts_primary_state_ids,
    .name = "plo",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
