/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 40
#define LARGE_STATE_COUNT 25
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_name = 1,
  anon_sym_is = 2,
  anon_sym_has = 3,
  anon_sym_does = 4,
  anon_sym_must = 5,
  anon_sym_be = 6,
  anon_sym_do = 7,
  anon_sym_of = 8,
  anon_sym_at = 9,
  anon_sym_as = 10,
  anon_sym_by = 11,
  anon_sym_with = 12,
  anon_sym_for = 13,
  anon_sym_from = 14,
  anon_sym_to = 15,
  anon_sym_upto = 16,
  anon_sym_downto = 17,
  anon_sym_in = 18,
  anon_sym_out = 19,
  anon_sym_into = 20,
  anon_sym_outof = 21,
  anon_sym_on = 22,
  anon_sym_off = 23,
  anon_sym_AMP = 24,
  aux_sym_out_dependency_token1 = 25,
  anon_sym_STAR = 26,
  anon_sym_DQUOTE = 27,
  aux_sym_string_token1 = 28,
  aux_sym_string_token2 = 29,
  aux_sym_string_block_token1 = 30,
  anon_sym_DASH_DASH = 31,
  anon_sym_BSLASH_LPAREN = 32,
  anon_sym_RPAREN = 33,
  anon_sym_LPAREN = 34,
  anon_sym_COLON = 35,
  sym_punctuation = 36,
  sym_comment = 37,
  sym_source_file = 38,
  sym__anything = 39,
  sym_keyword = 40,
  sym_out_dependency = 41,
  sym_implicit_dependency = 42,
  sym_string = 43,
  sym_string_block = 44,
  sym_interpolation = 45,
  sym_call = 46,
  sym_call_multi = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_string_repeat1 = 49,
  aux_sym_string_block_repeat1 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_name] = "name",
  [anon_sym_is] = "is",
  [anon_sym_has] = "has",
  [anon_sym_does] = "does",
  [anon_sym_must] = "must",
  [anon_sym_be] = "be",
  [anon_sym_do] = "do",
  [anon_sym_of] = "of",
  [anon_sym_at] = "at",
  [anon_sym_as] = "as",
  [anon_sym_by] = "by",
  [anon_sym_with] = "with",
  [anon_sym_for] = "for",
  [anon_sym_from] = "from",
  [anon_sym_to] = "to",
  [anon_sym_upto] = "upto",
  [anon_sym_downto] = "downto",
  [anon_sym_in] = "in",
  [anon_sym_out] = "out",
  [anon_sym_into] = "into",
  [anon_sym_outof] = "outof",
  [anon_sym_on] = "on",
  [anon_sym_off] = "off",
  [anon_sym_AMP] = "&",
  [aux_sym_out_dependency_token1] = "out_dependency_token1",
  [anon_sym_STAR] = "*",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [aux_sym_string_block_token1] = "string_block_token1",
  [anon_sym_DASH_DASH] = "--",
  [anon_sym_BSLASH_LPAREN] = "\\(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COLON] = ":",
  [sym_punctuation] = "punctuation",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__anything] = "_anything",
  [sym_keyword] = "keyword",
  [sym_out_dependency] = "out_dependency",
  [sym_implicit_dependency] = "implicit_dependency",
  [sym_string] = "string",
  [sym_string_block] = "string_block",
  [sym_interpolation] = "interpolation",
  [sym_call] = "call",
  [sym_call_multi] = "call_multi",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_block_repeat1] = "string_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_name] = sym_name,
  [anon_sym_is] = anon_sym_is,
  [anon_sym_has] = anon_sym_has,
  [anon_sym_does] = anon_sym_does,
  [anon_sym_must] = anon_sym_must,
  [anon_sym_be] = anon_sym_be,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_of] = anon_sym_of,
  [anon_sym_at] = anon_sym_at,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_by] = anon_sym_by,
  [anon_sym_with] = anon_sym_with,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_to] = anon_sym_to,
  [anon_sym_upto] = anon_sym_upto,
  [anon_sym_downto] = anon_sym_downto,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_out] = anon_sym_out,
  [anon_sym_into] = anon_sym_into,
  [anon_sym_outof] = anon_sym_outof,
  [anon_sym_on] = anon_sym_on,
  [anon_sym_off] = anon_sym_off,
  [anon_sym_AMP] = anon_sym_AMP,
  [aux_sym_out_dependency_token1] = aux_sym_out_dependency_token1,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [aux_sym_string_block_token1] = aux_sym_string_block_token1,
  [anon_sym_DASH_DASH] = anon_sym_DASH_DASH,
  [anon_sym_BSLASH_LPAREN] = anon_sym_BSLASH_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_punctuation] = sym_punctuation,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__anything] = sym__anything,
  [sym_keyword] = sym_keyword,
  [sym_out_dependency] = sym_out_dependency,
  [sym_implicit_dependency] = sym_implicit_dependency,
  [sym_string] = sym_string,
  [sym_string_block] = sym_string_block,
  [sym_interpolation] = sym_interpolation,
  [sym_call] = sym_call,
  [sym_call_multi] = sym_call_multi,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_block_repeat1] = aux_sym_string_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_is] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_has] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_does] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_must] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_be] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_of] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_at] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_by] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_with] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_to] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_upto] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_downto] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_out] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_into] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_outof] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_on] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_off] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_out_dependency_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_block_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__anything] = {
    .visible = false,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_out_dependency] = {
    .visible = true,
    .named = true,
  },
  [sym_implicit_dependency] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string_block] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_call_multi] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_func = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_func] = "func",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_func, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 13,
  [17] = 11,
  [18] = 9,
  [19] = 10,
  [20] = 12,
  [21] = 14,
  [22] = 22,
  [23] = 22,
  [24] = 15,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 25,
  [29] = 26,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 32,
  [35] = 35,
  [36] = 35,
  [37] = 37,
  [38] = 38,
  [39] = 37,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 17,
        '&', 14,
        '(', 25,
        ')', 24,
        '*', 16,
        '-', 4,
        ':', 26,
        '\\', 3,
        '`', 28,
        ',', 27,
        '.', 27,
        '/', 27,
        ';', 27,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 17,
        '&', 14,
        ')', 24,
        '*', 16,
        '-', 7,
        '`', 28,
        '(', 27,
        ',', 27,
        '.', 27,
        '/', 27,
        ':', 27,
        ';', 27,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(23);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == '`') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == '`') ADVANCE(21);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 9:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 17,
        '&', 14,
        '(', 25,
        '*', 16,
        '-', 7,
        ':', 26,
        '`', 28,
        ')', 27,
        ',', 27,
        '.', 27,
        '/', 27,
        ';', 27,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 10:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 17,
        '&', 14,
        ')', 24,
        '*', 16,
        '-', 4,
        '\\', 3,
        '`', 28,
        '(', 27,
        ',', 27,
        '.', 27,
        '/', 27,
        ':', 27,
        ';', 27,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '&') ADVANCE(14);
      if (lookahead == '*') ADVANCE(16);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '`') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (lookahead == '(' ||
          lookahead == ')' ||
          (',' <= lookahead && lookahead <= '/') ||
          lookahead == ':' ||
          lookahead == ';') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_out_dependency_token1);
      if (lookahead == '-') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_string_block_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_BSLASH_LPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_punctuation);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'd', 3,
        'f', 4,
        'h', 5,
        'i', 6,
        'm', 7,
        'o', 8,
        't', 9,
        'u', 10,
        'w', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 's') ADVANCE(12);
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(14);
      if (lookahead == 'y') ADVANCE(15);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(17);
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(20);
      if (lookahead == 's') ADVANCE(21);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 8:
      if (lookahead == 'f') ADVANCE(23);
      if (lookahead == 'n') ADVANCE(24);
      if (lookahead == 'u') ADVANCE(25);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 10:
      if (lookahead == 'p') ADVANCE(27);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_at);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_be);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_by);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_do);
      if (lookahead == 'e') ADVANCE(29);
      if (lookahead == 'w') ADVANCE(30);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 19:
      if (lookahead == 's') ADVANCE(33);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_is);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(35);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_of);
      if (lookahead == 'f') ADVANCE(36);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_on);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_to);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(40);
      END_STATE();
    case 30:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 32:
      if (lookahead == 'm') ADVANCE(42);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_has);
      END_STATE();
    case 34:
      if (lookahead == 'o') ADVANCE(43);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(44);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_off);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_out);
      if (lookahead == 'o') ADVANCE(45);
      END_STATE();
    case 38:
      if (lookahead == 'o') ADVANCE(46);
      END_STATE();
    case 39:
      if (lookahead == 'h') ADVANCE(47);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_does);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(48);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_into);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_must);
      END_STATE();
    case 45:
      if (lookahead == 'f') ADVANCE(49);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_upto);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_with);
      END_STATE();
    case 48:
      if (lookahead == 'o') ADVANCE(50);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_outof);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_downto);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 9},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 11},
  [11] = {.lex_state = 11},
  [12] = {.lex_state = 11},
  [13] = {.lex_state = 11},
  [14] = {.lex_state = 11},
  [15] = {.lex_state = 11},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 11},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 8},
  [36] = {.lex_state = 8},
  [37] = {.lex_state = 8},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [anon_sym_is] = ACTIONS(1),
    [anon_sym_has] = ACTIONS(1),
    [anon_sym_does] = ACTIONS(1),
    [anon_sym_must] = ACTIONS(1),
    [anon_sym_be] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_of] = ACTIONS(1),
    [anon_sym_at] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_by] = ACTIONS(1),
    [anon_sym_with] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_to] = ACTIONS(1),
    [anon_sym_upto] = ACTIONS(1),
    [anon_sym_downto] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_out] = ACTIONS(1),
    [anon_sym_into] = ACTIONS(1),
    [anon_sym_outof] = ACTIONS(1),
    [anon_sym_on] = ACTIONS(1),
    [anon_sym_off] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [aux_sym_string_block_token1] = ACTIONS(1),
    [anon_sym_DASH_DASH] = ACTIONS(1),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_punctuation] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(38),
    [sym__anything] = STATE(3),
    [sym_keyword] = STATE(3),
    [sym_out_dependency] = STATE(3),
    [sym_implicit_dependency] = STATE(3),
    [sym_string] = STATE(3),
    [sym_string_block] = STATE(3),
    [sym_call] = STATE(3),
    [sym_call_multi] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_string_block_repeat1] = STATE(34),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_name] = ACTIONS(5),
    [anon_sym_is] = ACTIONS(7),
    [anon_sym_has] = ACTIONS(7),
    [anon_sym_does] = ACTIONS(7),
    [anon_sym_must] = ACTIONS(7),
    [anon_sym_be] = ACTIONS(7),
    [anon_sym_do] = ACTIONS(7),
    [anon_sym_of] = ACTIONS(7),
    [anon_sym_at] = ACTIONS(7),
    [anon_sym_as] = ACTIONS(7),
    [anon_sym_by] = ACTIONS(7),
    [anon_sym_with] = ACTIONS(7),
    [anon_sym_for] = ACTIONS(7),
    [anon_sym_from] = ACTIONS(7),
    [anon_sym_to] = ACTIONS(7),
    [anon_sym_upto] = ACTIONS(7),
    [anon_sym_downto] = ACTIONS(7),
    [anon_sym_in] = ACTIONS(7),
    [anon_sym_out] = ACTIONS(7),
    [anon_sym_into] = ACTIONS(7),
    [anon_sym_outof] = ACTIONS(7),
    [anon_sym_on] = ACTIONS(7),
    [anon_sym_off] = ACTIONS(7),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [aux_sym_string_block_token1] = ACTIONS(15),
    [sym_punctuation] = ACTIONS(17),
    [sym_comment] = ACTIONS(17),
  },
  [STATE(2)] = {
    [sym__anything] = STATE(5),
    [sym_keyword] = STATE(5),
    [sym_out_dependency] = STATE(5),
    [sym_implicit_dependency] = STATE(5),
    [sym_string] = STATE(5),
    [sym_string_block] = STATE(5),
    [sym_call] = STATE(5),
    [sym_call_multi] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [aux_sym_string_block_repeat1] = STATE(32),
    [sym_name] = ACTIONS(19),
    [anon_sym_is] = ACTIONS(21),
    [anon_sym_has] = ACTIONS(21),
    [anon_sym_does] = ACTIONS(21),
    [anon_sym_must] = ACTIONS(21),
    [anon_sym_be] = ACTIONS(21),
    [anon_sym_do] = ACTIONS(21),
    [anon_sym_of] = ACTIONS(21),
    [anon_sym_at] = ACTIONS(21),
    [anon_sym_as] = ACTIONS(21),
    [anon_sym_by] = ACTIONS(21),
    [anon_sym_with] = ACTIONS(21),
    [anon_sym_for] = ACTIONS(21),
    [anon_sym_from] = ACTIONS(21),
    [anon_sym_to] = ACTIONS(21),
    [anon_sym_upto] = ACTIONS(21),
    [anon_sym_downto] = ACTIONS(21),
    [anon_sym_in] = ACTIONS(21),
    [anon_sym_out] = ACTIONS(21),
    [anon_sym_into] = ACTIONS(21),
    [anon_sym_outof] = ACTIONS(21),
    [anon_sym_on] = ACTIONS(21),
    [anon_sym_off] = ACTIONS(21),
    [anon_sym_AMP] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [aux_sym_string_block_token1] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(31),
    [sym_punctuation] = ACTIONS(33),
    [sym_comment] = ACTIONS(35),
  },
  [STATE(3)] = {
    [sym__anything] = STATE(4),
    [sym_keyword] = STATE(4),
    [sym_out_dependency] = STATE(4),
    [sym_implicit_dependency] = STATE(4),
    [sym_string] = STATE(4),
    [sym_string_block] = STATE(4),
    [sym_call] = STATE(4),
    [sym_call_multi] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [aux_sym_string_block_repeat1] = STATE(34),
    [ts_builtin_sym_end] = ACTIONS(37),
    [sym_name] = ACTIONS(5),
    [anon_sym_is] = ACTIONS(7),
    [anon_sym_has] = ACTIONS(7),
    [anon_sym_does] = ACTIONS(7),
    [anon_sym_must] = ACTIONS(7),
    [anon_sym_be] = ACTIONS(7),
    [anon_sym_do] = ACTIONS(7),
    [anon_sym_of] = ACTIONS(7),
    [anon_sym_at] = ACTIONS(7),
    [anon_sym_as] = ACTIONS(7),
    [anon_sym_by] = ACTIONS(7),
    [anon_sym_with] = ACTIONS(7),
    [anon_sym_for] = ACTIONS(7),
    [anon_sym_from] = ACTIONS(7),
    [anon_sym_to] = ACTIONS(7),
    [anon_sym_upto] = ACTIONS(7),
    [anon_sym_downto] = ACTIONS(7),
    [anon_sym_in] = ACTIONS(7),
    [anon_sym_out] = ACTIONS(7),
    [anon_sym_into] = ACTIONS(7),
    [anon_sym_outof] = ACTIONS(7),
    [anon_sym_on] = ACTIONS(7),
    [anon_sym_off] = ACTIONS(7),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [aux_sym_string_block_token1] = ACTIONS(15),
    [sym_punctuation] = ACTIONS(39),
    [sym_comment] = ACTIONS(39),
  },
  [STATE(4)] = {
    [sym__anything] = STATE(4),
    [sym_keyword] = STATE(4),
    [sym_out_dependency] = STATE(4),
    [sym_implicit_dependency] = STATE(4),
    [sym_string] = STATE(4),
    [sym_string_block] = STATE(4),
    [sym_call] = STATE(4),
    [sym_call_multi] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [aux_sym_string_block_repeat1] = STATE(34),
    [ts_builtin_sym_end] = ACTIONS(41),
    [sym_name] = ACTIONS(43),
    [anon_sym_is] = ACTIONS(46),
    [anon_sym_has] = ACTIONS(46),
    [anon_sym_does] = ACTIONS(46),
    [anon_sym_must] = ACTIONS(46),
    [anon_sym_be] = ACTIONS(46),
    [anon_sym_do] = ACTIONS(46),
    [anon_sym_of] = ACTIONS(46),
    [anon_sym_at] = ACTIONS(46),
    [anon_sym_as] = ACTIONS(46),
    [anon_sym_by] = ACTIONS(46),
    [anon_sym_with] = ACTIONS(46),
    [anon_sym_for] = ACTIONS(46),
    [anon_sym_from] = ACTIONS(46),
    [anon_sym_to] = ACTIONS(46),
    [anon_sym_upto] = ACTIONS(46),
    [anon_sym_downto] = ACTIONS(46),
    [anon_sym_in] = ACTIONS(46),
    [anon_sym_out] = ACTIONS(46),
    [anon_sym_into] = ACTIONS(46),
    [anon_sym_outof] = ACTIONS(46),
    [anon_sym_on] = ACTIONS(46),
    [anon_sym_off] = ACTIONS(46),
    [anon_sym_AMP] = ACTIONS(49),
    [anon_sym_STAR] = ACTIONS(52),
    [anon_sym_DQUOTE] = ACTIONS(55),
    [aux_sym_string_block_token1] = ACTIONS(58),
    [sym_punctuation] = ACTIONS(61),
    [sym_comment] = ACTIONS(61),
  },
  [STATE(5)] = {
    [sym__anything] = STATE(6),
    [sym_keyword] = STATE(6),
    [sym_out_dependency] = STATE(6),
    [sym_implicit_dependency] = STATE(6),
    [sym_string] = STATE(6),
    [sym_string_block] = STATE(6),
    [sym_call] = STATE(6),
    [sym_call_multi] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_string_block_repeat1] = STATE(32),
    [sym_name] = ACTIONS(19),
    [anon_sym_is] = ACTIONS(21),
    [anon_sym_has] = ACTIONS(21),
    [anon_sym_does] = ACTIONS(21),
    [anon_sym_must] = ACTIONS(21),
    [anon_sym_be] = ACTIONS(21),
    [anon_sym_do] = ACTIONS(21),
    [anon_sym_of] = ACTIONS(21),
    [anon_sym_at] = ACTIONS(21),
    [anon_sym_as] = ACTIONS(21),
    [anon_sym_by] = ACTIONS(21),
    [anon_sym_with] = ACTIONS(21),
    [anon_sym_for] = ACTIONS(21),
    [anon_sym_from] = ACTIONS(21),
    [anon_sym_to] = ACTIONS(21),
    [anon_sym_upto] = ACTIONS(21),
    [anon_sym_downto] = ACTIONS(21),
    [anon_sym_in] = ACTIONS(21),
    [anon_sym_out] = ACTIONS(21),
    [anon_sym_into] = ACTIONS(21),
    [anon_sym_outof] = ACTIONS(21),
    [anon_sym_on] = ACTIONS(21),
    [anon_sym_off] = ACTIONS(21),
    [anon_sym_AMP] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [aux_sym_string_block_token1] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(64),
    [sym_punctuation] = ACTIONS(66),
    [sym_comment] = ACTIONS(68),
  },
  [STATE(6)] = {
    [sym__anything] = STATE(6),
    [sym_keyword] = STATE(6),
    [sym_out_dependency] = STATE(6),
    [sym_implicit_dependency] = STATE(6),
    [sym_string] = STATE(6),
    [sym_string_block] = STATE(6),
    [sym_call] = STATE(6),
    [sym_call_multi] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_string_block_repeat1] = STATE(32),
    [sym_name] = ACTIONS(70),
    [anon_sym_is] = ACTIONS(73),
    [anon_sym_has] = ACTIONS(73),
    [anon_sym_does] = ACTIONS(73),
    [anon_sym_must] = ACTIONS(73),
    [anon_sym_be] = ACTIONS(73),
    [anon_sym_do] = ACTIONS(73),
    [anon_sym_of] = ACTIONS(73),
    [anon_sym_at] = ACTIONS(73),
    [anon_sym_as] = ACTIONS(73),
    [anon_sym_by] = ACTIONS(73),
    [anon_sym_with] = ACTIONS(73),
    [anon_sym_for] = ACTIONS(73),
    [anon_sym_from] = ACTIONS(73),
    [anon_sym_to] = ACTIONS(73),
    [anon_sym_upto] = ACTIONS(73),
    [anon_sym_downto] = ACTIONS(73),
    [anon_sym_in] = ACTIONS(73),
    [anon_sym_out] = ACTIONS(73),
    [anon_sym_into] = ACTIONS(73),
    [anon_sym_outof] = ACTIONS(73),
    [anon_sym_on] = ACTIONS(73),
    [anon_sym_off] = ACTIONS(73),
    [anon_sym_AMP] = ACTIONS(76),
    [anon_sym_STAR] = ACTIONS(79),
    [anon_sym_DQUOTE] = ACTIONS(82),
    [aux_sym_string_block_token1] = ACTIONS(85),
    [anon_sym_RPAREN] = ACTIONS(41),
    [sym_punctuation] = ACTIONS(88),
    [sym_comment] = ACTIONS(91),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(94),
    [sym_name] = ACTIONS(96),
    [anon_sym_is] = ACTIONS(96),
    [anon_sym_has] = ACTIONS(96),
    [anon_sym_does] = ACTIONS(96),
    [anon_sym_must] = ACTIONS(96),
    [anon_sym_be] = ACTIONS(96),
    [anon_sym_do] = ACTIONS(96),
    [anon_sym_of] = ACTIONS(96),
    [anon_sym_at] = ACTIONS(96),
    [anon_sym_as] = ACTIONS(96),
    [anon_sym_by] = ACTIONS(96),
    [anon_sym_with] = ACTIONS(96),
    [anon_sym_for] = ACTIONS(96),
    [anon_sym_from] = ACTIONS(96),
    [anon_sym_to] = ACTIONS(96),
    [anon_sym_upto] = ACTIONS(96),
    [anon_sym_downto] = ACTIONS(96),
    [anon_sym_in] = ACTIONS(96),
    [anon_sym_out] = ACTIONS(96),
    [anon_sym_into] = ACTIONS(96),
    [anon_sym_outof] = ACTIONS(96),
    [anon_sym_on] = ACTIONS(96),
    [anon_sym_off] = ACTIONS(96),
    [anon_sym_AMP] = ACTIONS(94),
    [anon_sym_STAR] = ACTIONS(94),
    [anon_sym_DQUOTE] = ACTIONS(94),
    [aux_sym_string_block_token1] = ACTIONS(94),
    [anon_sym_LPAREN] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(100),
    [sym_punctuation] = ACTIONS(96),
    [sym_comment] = ACTIONS(94),
  },
  [STATE(8)] = {
    [sym_name] = ACTIONS(96),
    [anon_sym_is] = ACTIONS(96),
    [anon_sym_has] = ACTIONS(96),
    [anon_sym_does] = ACTIONS(96),
    [anon_sym_must] = ACTIONS(96),
    [anon_sym_be] = ACTIONS(96),
    [anon_sym_do] = ACTIONS(96),
    [anon_sym_of] = ACTIONS(96),
    [anon_sym_at] = ACTIONS(96),
    [anon_sym_as] = ACTIONS(96),
    [anon_sym_by] = ACTIONS(96),
    [anon_sym_with] = ACTIONS(96),
    [anon_sym_for] = ACTIONS(96),
    [anon_sym_from] = ACTIONS(96),
    [anon_sym_to] = ACTIONS(96),
    [anon_sym_upto] = ACTIONS(96),
    [anon_sym_downto] = ACTIONS(96),
    [anon_sym_in] = ACTIONS(96),
    [anon_sym_out] = ACTIONS(96),
    [anon_sym_into] = ACTIONS(96),
    [anon_sym_outof] = ACTIONS(96),
    [anon_sym_on] = ACTIONS(96),
    [anon_sym_off] = ACTIONS(96),
    [anon_sym_AMP] = ACTIONS(94),
    [anon_sym_STAR] = ACTIONS(94),
    [anon_sym_DQUOTE] = ACTIONS(94),
    [aux_sym_string_block_token1] = ACTIONS(94),
    [anon_sym_RPAREN] = ACTIONS(94),
    [anon_sym_LPAREN] = ACTIONS(102),
    [anon_sym_COLON] = ACTIONS(104),
    [sym_punctuation] = ACTIONS(96),
    [sym_comment] = ACTIONS(94),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(106),
    [sym_name] = ACTIONS(108),
    [anon_sym_is] = ACTIONS(108),
    [anon_sym_has] = ACTIONS(108),
    [anon_sym_does] = ACTIONS(108),
    [anon_sym_must] = ACTIONS(108),
    [anon_sym_be] = ACTIONS(108),
    [anon_sym_do] = ACTIONS(108),
    [anon_sym_of] = ACTIONS(108),
    [anon_sym_at] = ACTIONS(108),
    [anon_sym_as] = ACTIONS(108),
    [anon_sym_by] = ACTIONS(108),
    [anon_sym_with] = ACTIONS(108),
    [anon_sym_for] = ACTIONS(108),
    [anon_sym_from] = ACTIONS(108),
    [anon_sym_to] = ACTIONS(108),
    [anon_sym_upto] = ACTIONS(108),
    [anon_sym_downto] = ACTIONS(108),
    [anon_sym_in] = ACTIONS(108),
    [anon_sym_out] = ACTIONS(108),
    [anon_sym_into] = ACTIONS(108),
    [anon_sym_outof] = ACTIONS(108),
    [anon_sym_on] = ACTIONS(108),
    [anon_sym_off] = ACTIONS(108),
    [anon_sym_AMP] = ACTIONS(106),
    [anon_sym_STAR] = ACTIONS(106),
    [anon_sym_DQUOTE] = ACTIONS(106),
    [aux_sym_string_block_token1] = ACTIONS(106),
    [sym_punctuation] = ACTIONS(106),
    [sym_comment] = ACTIONS(106),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(110),
    [sym_name] = ACTIONS(112),
    [anon_sym_is] = ACTIONS(112),
    [anon_sym_has] = ACTIONS(112),
    [anon_sym_does] = ACTIONS(112),
    [anon_sym_must] = ACTIONS(112),
    [anon_sym_be] = ACTIONS(112),
    [anon_sym_do] = ACTIONS(112),
    [anon_sym_of] = ACTIONS(112),
    [anon_sym_at] = ACTIONS(112),
    [anon_sym_as] = ACTIONS(112),
    [anon_sym_by] = ACTIONS(112),
    [anon_sym_with] = ACTIONS(112),
    [anon_sym_for] = ACTIONS(112),
    [anon_sym_from] = ACTIONS(112),
    [anon_sym_to] = ACTIONS(112),
    [anon_sym_upto] = ACTIONS(112),
    [anon_sym_downto] = ACTIONS(112),
    [anon_sym_in] = ACTIONS(112),
    [anon_sym_out] = ACTIONS(112),
    [anon_sym_into] = ACTIONS(112),
    [anon_sym_outof] = ACTIONS(112),
    [anon_sym_on] = ACTIONS(112),
    [anon_sym_off] = ACTIONS(112),
    [anon_sym_AMP] = ACTIONS(110),
    [anon_sym_STAR] = ACTIONS(110),
    [anon_sym_DQUOTE] = ACTIONS(110),
    [aux_sym_string_block_token1] = ACTIONS(110),
    [sym_punctuation] = ACTIONS(110),
    [sym_comment] = ACTIONS(110),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(114),
    [sym_name] = ACTIONS(116),
    [anon_sym_is] = ACTIONS(116),
    [anon_sym_has] = ACTIONS(116),
    [anon_sym_does] = ACTIONS(116),
    [anon_sym_must] = ACTIONS(116),
    [anon_sym_be] = ACTIONS(116),
    [anon_sym_do] = ACTIONS(116),
    [anon_sym_of] = ACTIONS(116),
    [anon_sym_at] = ACTIONS(116),
    [anon_sym_as] = ACTIONS(116),
    [anon_sym_by] = ACTIONS(116),
    [anon_sym_with] = ACTIONS(116),
    [anon_sym_for] = ACTIONS(116),
    [anon_sym_from] = ACTIONS(116),
    [anon_sym_to] = ACTIONS(116),
    [anon_sym_upto] = ACTIONS(116),
    [anon_sym_downto] = ACTIONS(116),
    [anon_sym_in] = ACTIONS(116),
    [anon_sym_out] = ACTIONS(116),
    [anon_sym_into] = ACTIONS(116),
    [anon_sym_outof] = ACTIONS(116),
    [anon_sym_on] = ACTIONS(116),
    [anon_sym_off] = ACTIONS(116),
    [anon_sym_AMP] = ACTIONS(114),
    [anon_sym_STAR] = ACTIONS(114),
    [anon_sym_DQUOTE] = ACTIONS(114),
    [aux_sym_string_block_token1] = ACTIONS(114),
    [sym_punctuation] = ACTIONS(114),
    [sym_comment] = ACTIONS(114),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(118),
    [sym_name] = ACTIONS(120),
    [anon_sym_is] = ACTIONS(120),
    [anon_sym_has] = ACTIONS(120),
    [anon_sym_does] = ACTIONS(120),
    [anon_sym_must] = ACTIONS(120),
    [anon_sym_be] = ACTIONS(120),
    [anon_sym_do] = ACTIONS(120),
    [anon_sym_of] = ACTIONS(120),
    [anon_sym_at] = ACTIONS(120),
    [anon_sym_as] = ACTIONS(120),
    [anon_sym_by] = ACTIONS(120),
    [anon_sym_with] = ACTIONS(120),
    [anon_sym_for] = ACTIONS(120),
    [anon_sym_from] = ACTIONS(120),
    [anon_sym_to] = ACTIONS(120),
    [anon_sym_upto] = ACTIONS(120),
    [anon_sym_downto] = ACTIONS(120),
    [anon_sym_in] = ACTIONS(120),
    [anon_sym_out] = ACTIONS(120),
    [anon_sym_into] = ACTIONS(120),
    [anon_sym_outof] = ACTIONS(120),
    [anon_sym_on] = ACTIONS(120),
    [anon_sym_off] = ACTIONS(120),
    [anon_sym_AMP] = ACTIONS(118),
    [anon_sym_STAR] = ACTIONS(118),
    [anon_sym_DQUOTE] = ACTIONS(118),
    [aux_sym_string_block_token1] = ACTIONS(118),
    [sym_punctuation] = ACTIONS(118),
    [sym_comment] = ACTIONS(118),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(122),
    [sym_name] = ACTIONS(124),
    [anon_sym_is] = ACTIONS(124),
    [anon_sym_has] = ACTIONS(124),
    [anon_sym_does] = ACTIONS(124),
    [anon_sym_must] = ACTIONS(124),
    [anon_sym_be] = ACTIONS(124),
    [anon_sym_do] = ACTIONS(124),
    [anon_sym_of] = ACTIONS(124),
    [anon_sym_at] = ACTIONS(124),
    [anon_sym_as] = ACTIONS(124),
    [anon_sym_by] = ACTIONS(124),
    [anon_sym_with] = ACTIONS(124),
    [anon_sym_for] = ACTIONS(124),
    [anon_sym_from] = ACTIONS(124),
    [anon_sym_to] = ACTIONS(124),
    [anon_sym_upto] = ACTIONS(124),
    [anon_sym_downto] = ACTIONS(124),
    [anon_sym_in] = ACTIONS(124),
    [anon_sym_out] = ACTIONS(124),
    [anon_sym_into] = ACTIONS(124),
    [anon_sym_outof] = ACTIONS(124),
    [anon_sym_on] = ACTIONS(124),
    [anon_sym_off] = ACTIONS(124),
    [anon_sym_AMP] = ACTIONS(122),
    [anon_sym_STAR] = ACTIONS(122),
    [anon_sym_DQUOTE] = ACTIONS(122),
    [aux_sym_string_block_token1] = ACTIONS(122),
    [sym_punctuation] = ACTIONS(122),
    [sym_comment] = ACTIONS(122),
  },
  [STATE(14)] = {
    [ts_builtin_sym_end] = ACTIONS(126),
    [sym_name] = ACTIONS(128),
    [anon_sym_is] = ACTIONS(128),
    [anon_sym_has] = ACTIONS(128),
    [anon_sym_does] = ACTIONS(128),
    [anon_sym_must] = ACTIONS(128),
    [anon_sym_be] = ACTIONS(128),
    [anon_sym_do] = ACTIONS(128),
    [anon_sym_of] = ACTIONS(128),
    [anon_sym_at] = ACTIONS(128),
    [anon_sym_as] = ACTIONS(128),
    [anon_sym_by] = ACTIONS(128),
    [anon_sym_with] = ACTIONS(128),
    [anon_sym_for] = ACTIONS(128),
    [anon_sym_from] = ACTIONS(128),
    [anon_sym_to] = ACTIONS(128),
    [anon_sym_upto] = ACTIONS(128),
    [anon_sym_downto] = ACTIONS(128),
    [anon_sym_in] = ACTIONS(128),
    [anon_sym_out] = ACTIONS(128),
    [anon_sym_into] = ACTIONS(128),
    [anon_sym_outof] = ACTIONS(128),
    [anon_sym_on] = ACTIONS(128),
    [anon_sym_off] = ACTIONS(128),
    [anon_sym_AMP] = ACTIONS(126),
    [anon_sym_STAR] = ACTIONS(126),
    [anon_sym_DQUOTE] = ACTIONS(126),
    [aux_sym_string_block_token1] = ACTIONS(126),
    [sym_punctuation] = ACTIONS(126),
    [sym_comment] = ACTIONS(126),
  },
  [STATE(15)] = {
    [ts_builtin_sym_end] = ACTIONS(130),
    [sym_name] = ACTIONS(132),
    [anon_sym_is] = ACTIONS(132),
    [anon_sym_has] = ACTIONS(132),
    [anon_sym_does] = ACTIONS(132),
    [anon_sym_must] = ACTIONS(132),
    [anon_sym_be] = ACTIONS(132),
    [anon_sym_do] = ACTIONS(132),
    [anon_sym_of] = ACTIONS(132),
    [anon_sym_at] = ACTIONS(132),
    [anon_sym_as] = ACTIONS(132),
    [anon_sym_by] = ACTIONS(132),
    [anon_sym_with] = ACTIONS(132),
    [anon_sym_for] = ACTIONS(132),
    [anon_sym_from] = ACTIONS(132),
    [anon_sym_to] = ACTIONS(132),
    [anon_sym_upto] = ACTIONS(132),
    [anon_sym_downto] = ACTIONS(132),
    [anon_sym_in] = ACTIONS(132),
    [anon_sym_out] = ACTIONS(132),
    [anon_sym_into] = ACTIONS(132),
    [anon_sym_outof] = ACTIONS(132),
    [anon_sym_on] = ACTIONS(132),
    [anon_sym_off] = ACTIONS(132),
    [anon_sym_AMP] = ACTIONS(130),
    [anon_sym_STAR] = ACTIONS(130),
    [anon_sym_DQUOTE] = ACTIONS(130),
    [aux_sym_string_block_token1] = ACTIONS(130),
    [sym_punctuation] = ACTIONS(130),
    [sym_comment] = ACTIONS(130),
  },
  [STATE(16)] = {
    [sym_name] = ACTIONS(124),
    [anon_sym_is] = ACTIONS(124),
    [anon_sym_has] = ACTIONS(124),
    [anon_sym_does] = ACTIONS(124),
    [anon_sym_must] = ACTIONS(124),
    [anon_sym_be] = ACTIONS(124),
    [anon_sym_do] = ACTIONS(124),
    [anon_sym_of] = ACTIONS(124),
    [anon_sym_at] = ACTIONS(124),
    [anon_sym_as] = ACTIONS(124),
    [anon_sym_by] = ACTIONS(124),
    [anon_sym_with] = ACTIONS(124),
    [anon_sym_for] = ACTIONS(124),
    [anon_sym_from] = ACTIONS(124),
    [anon_sym_to] = ACTIONS(124),
    [anon_sym_upto] = ACTIONS(124),
    [anon_sym_downto] = ACTIONS(124),
    [anon_sym_in] = ACTIONS(124),
    [anon_sym_out] = ACTIONS(124),
    [anon_sym_into] = ACTIONS(124),
    [anon_sym_outof] = ACTIONS(124),
    [anon_sym_on] = ACTIONS(124),
    [anon_sym_off] = ACTIONS(124),
    [anon_sym_AMP] = ACTIONS(122),
    [anon_sym_STAR] = ACTIONS(122),
    [anon_sym_DQUOTE] = ACTIONS(122),
    [aux_sym_string_block_token1] = ACTIONS(122),
    [anon_sym_RPAREN] = ACTIONS(122),
    [sym_punctuation] = ACTIONS(124),
    [sym_comment] = ACTIONS(122),
  },
  [STATE(17)] = {
    [sym_name] = ACTIONS(116),
    [anon_sym_is] = ACTIONS(116),
    [anon_sym_has] = ACTIONS(116),
    [anon_sym_does] = ACTIONS(116),
    [anon_sym_must] = ACTIONS(116),
    [anon_sym_be] = ACTIONS(116),
    [anon_sym_do] = ACTIONS(116),
    [anon_sym_of] = ACTIONS(116),
    [anon_sym_at] = ACTIONS(116),
    [anon_sym_as] = ACTIONS(116),
    [anon_sym_by] = ACTIONS(116),
    [anon_sym_with] = ACTIONS(116),
    [anon_sym_for] = ACTIONS(116),
    [anon_sym_from] = ACTIONS(116),
    [anon_sym_to] = ACTIONS(116),
    [anon_sym_upto] = ACTIONS(116),
    [anon_sym_downto] = ACTIONS(116),
    [anon_sym_in] = ACTIONS(116),
    [anon_sym_out] = ACTIONS(116),
    [anon_sym_into] = ACTIONS(116),
    [anon_sym_outof] = ACTIONS(116),
    [anon_sym_on] = ACTIONS(116),
    [anon_sym_off] = ACTIONS(116),
    [anon_sym_AMP] = ACTIONS(114),
    [anon_sym_STAR] = ACTIONS(114),
    [anon_sym_DQUOTE] = ACTIONS(114),
    [aux_sym_string_block_token1] = ACTIONS(114),
    [anon_sym_RPAREN] = ACTIONS(114),
    [sym_punctuation] = ACTIONS(116),
    [sym_comment] = ACTIONS(114),
  },
  [STATE(18)] = {
    [sym_name] = ACTIONS(108),
    [anon_sym_is] = ACTIONS(108),
    [anon_sym_has] = ACTIONS(108),
    [anon_sym_does] = ACTIONS(108),
    [anon_sym_must] = ACTIONS(108),
    [anon_sym_be] = ACTIONS(108),
    [anon_sym_do] = ACTIONS(108),
    [anon_sym_of] = ACTIONS(108),
    [anon_sym_at] = ACTIONS(108),
    [anon_sym_as] = ACTIONS(108),
    [anon_sym_by] = ACTIONS(108),
    [anon_sym_with] = ACTIONS(108),
    [anon_sym_for] = ACTIONS(108),
    [anon_sym_from] = ACTIONS(108),
    [anon_sym_to] = ACTIONS(108),
    [anon_sym_upto] = ACTIONS(108),
    [anon_sym_downto] = ACTIONS(108),
    [anon_sym_in] = ACTIONS(108),
    [anon_sym_out] = ACTIONS(108),
    [anon_sym_into] = ACTIONS(108),
    [anon_sym_outof] = ACTIONS(108),
    [anon_sym_on] = ACTIONS(108),
    [anon_sym_off] = ACTIONS(108),
    [anon_sym_AMP] = ACTIONS(106),
    [anon_sym_STAR] = ACTIONS(106),
    [anon_sym_DQUOTE] = ACTIONS(106),
    [aux_sym_string_block_token1] = ACTIONS(106),
    [anon_sym_RPAREN] = ACTIONS(106),
    [sym_punctuation] = ACTIONS(108),
    [sym_comment] = ACTIONS(106),
  },
  [STATE(19)] = {
    [sym_name] = ACTIONS(112),
    [anon_sym_is] = ACTIONS(112),
    [anon_sym_has] = ACTIONS(112),
    [anon_sym_does] = ACTIONS(112),
    [anon_sym_must] = ACTIONS(112),
    [anon_sym_be] = ACTIONS(112),
    [anon_sym_do] = ACTIONS(112),
    [anon_sym_of] = ACTIONS(112),
    [anon_sym_at] = ACTIONS(112),
    [anon_sym_as] = ACTIONS(112),
    [anon_sym_by] = ACTIONS(112),
    [anon_sym_with] = ACTIONS(112),
    [anon_sym_for] = ACTIONS(112),
    [anon_sym_from] = ACTIONS(112),
    [anon_sym_to] = ACTIONS(112),
    [anon_sym_upto] = ACTIONS(112),
    [anon_sym_downto] = ACTIONS(112),
    [anon_sym_in] = ACTIONS(112),
    [anon_sym_out] = ACTIONS(112),
    [anon_sym_into] = ACTIONS(112),
    [anon_sym_outof] = ACTIONS(112),
    [anon_sym_on] = ACTIONS(112),
    [anon_sym_off] = ACTIONS(112),
    [anon_sym_AMP] = ACTIONS(110),
    [anon_sym_STAR] = ACTIONS(110),
    [anon_sym_DQUOTE] = ACTIONS(110),
    [aux_sym_string_block_token1] = ACTIONS(110),
    [anon_sym_RPAREN] = ACTIONS(110),
    [sym_punctuation] = ACTIONS(112),
    [sym_comment] = ACTIONS(110),
  },
  [STATE(20)] = {
    [sym_name] = ACTIONS(120),
    [anon_sym_is] = ACTIONS(120),
    [anon_sym_has] = ACTIONS(120),
    [anon_sym_does] = ACTIONS(120),
    [anon_sym_must] = ACTIONS(120),
    [anon_sym_be] = ACTIONS(120),
    [anon_sym_do] = ACTIONS(120),
    [anon_sym_of] = ACTIONS(120),
    [anon_sym_at] = ACTIONS(120),
    [anon_sym_as] = ACTIONS(120),
    [anon_sym_by] = ACTIONS(120),
    [anon_sym_with] = ACTIONS(120),
    [anon_sym_for] = ACTIONS(120),
    [anon_sym_from] = ACTIONS(120),
    [anon_sym_to] = ACTIONS(120),
    [anon_sym_upto] = ACTIONS(120),
    [anon_sym_downto] = ACTIONS(120),
    [anon_sym_in] = ACTIONS(120),
    [anon_sym_out] = ACTIONS(120),
    [anon_sym_into] = ACTIONS(120),
    [anon_sym_outof] = ACTIONS(120),
    [anon_sym_on] = ACTIONS(120),
    [anon_sym_off] = ACTIONS(120),
    [anon_sym_AMP] = ACTIONS(118),
    [anon_sym_STAR] = ACTIONS(118),
    [anon_sym_DQUOTE] = ACTIONS(118),
    [aux_sym_string_block_token1] = ACTIONS(118),
    [anon_sym_RPAREN] = ACTIONS(118),
    [sym_punctuation] = ACTIONS(120),
    [sym_comment] = ACTIONS(118),
  },
  [STATE(21)] = {
    [sym_name] = ACTIONS(128),
    [anon_sym_is] = ACTIONS(128),
    [anon_sym_has] = ACTIONS(128),
    [anon_sym_does] = ACTIONS(128),
    [anon_sym_must] = ACTIONS(128),
    [anon_sym_be] = ACTIONS(128),
    [anon_sym_do] = ACTIONS(128),
    [anon_sym_of] = ACTIONS(128),
    [anon_sym_at] = ACTIONS(128),
    [anon_sym_as] = ACTIONS(128),
    [anon_sym_by] = ACTIONS(128),
    [anon_sym_with] = ACTIONS(128),
    [anon_sym_for] = ACTIONS(128),
    [anon_sym_from] = ACTIONS(128),
    [anon_sym_to] = ACTIONS(128),
    [anon_sym_upto] = ACTIONS(128),
    [anon_sym_downto] = ACTIONS(128),
    [anon_sym_in] = ACTIONS(128),
    [anon_sym_out] = ACTIONS(128),
    [anon_sym_into] = ACTIONS(128),
    [anon_sym_outof] = ACTIONS(128),
    [anon_sym_on] = ACTIONS(128),
    [anon_sym_off] = ACTIONS(128),
    [anon_sym_AMP] = ACTIONS(126),
    [anon_sym_STAR] = ACTIONS(126),
    [anon_sym_DQUOTE] = ACTIONS(126),
    [aux_sym_string_block_token1] = ACTIONS(126),
    [anon_sym_RPAREN] = ACTIONS(126),
    [sym_punctuation] = ACTIONS(128),
    [sym_comment] = ACTIONS(126),
  },
  [STATE(22)] = {
    [ts_builtin_sym_end] = ACTIONS(134),
    [sym_name] = ACTIONS(136),
    [anon_sym_is] = ACTIONS(136),
    [anon_sym_has] = ACTIONS(136),
    [anon_sym_does] = ACTIONS(136),
    [anon_sym_must] = ACTIONS(136),
    [anon_sym_be] = ACTIONS(136),
    [anon_sym_do] = ACTIONS(136),
    [anon_sym_of] = ACTIONS(136),
    [anon_sym_at] = ACTIONS(136),
    [anon_sym_as] = ACTIONS(136),
    [anon_sym_by] = ACTIONS(136),
    [anon_sym_with] = ACTIONS(136),
    [anon_sym_for] = ACTIONS(136),
    [anon_sym_from] = ACTIONS(136),
    [anon_sym_to] = ACTIONS(136),
    [anon_sym_upto] = ACTIONS(136),
    [anon_sym_downto] = ACTIONS(136),
    [anon_sym_in] = ACTIONS(136),
    [anon_sym_out] = ACTIONS(136),
    [anon_sym_into] = ACTIONS(136),
    [anon_sym_outof] = ACTIONS(136),
    [anon_sym_on] = ACTIONS(136),
    [anon_sym_off] = ACTIONS(136),
    [anon_sym_AMP] = ACTIONS(134),
    [anon_sym_STAR] = ACTIONS(134),
    [anon_sym_DQUOTE] = ACTIONS(134),
    [aux_sym_string_block_token1] = ACTIONS(134),
    [sym_punctuation] = ACTIONS(134),
    [sym_comment] = ACTIONS(134),
  },
  [STATE(23)] = {
    [sym_name] = ACTIONS(136),
    [anon_sym_is] = ACTIONS(136),
    [anon_sym_has] = ACTIONS(136),
    [anon_sym_does] = ACTIONS(136),
    [anon_sym_must] = ACTIONS(136),
    [anon_sym_be] = ACTIONS(136),
    [anon_sym_do] = ACTIONS(136),
    [anon_sym_of] = ACTIONS(136),
    [anon_sym_at] = ACTIONS(136),
    [anon_sym_as] = ACTIONS(136),
    [anon_sym_by] = ACTIONS(136),
    [anon_sym_with] = ACTIONS(136),
    [anon_sym_for] = ACTIONS(136),
    [anon_sym_from] = ACTIONS(136),
    [anon_sym_to] = ACTIONS(136),
    [anon_sym_upto] = ACTIONS(136),
    [anon_sym_downto] = ACTIONS(136),
    [anon_sym_in] = ACTIONS(136),
    [anon_sym_out] = ACTIONS(136),
    [anon_sym_into] = ACTIONS(136),
    [anon_sym_outof] = ACTIONS(136),
    [anon_sym_on] = ACTIONS(136),
    [anon_sym_off] = ACTIONS(136),
    [anon_sym_AMP] = ACTIONS(134),
    [anon_sym_STAR] = ACTIONS(134),
    [anon_sym_DQUOTE] = ACTIONS(134),
    [aux_sym_string_block_token1] = ACTIONS(134),
    [anon_sym_RPAREN] = ACTIONS(134),
    [sym_punctuation] = ACTIONS(136),
    [sym_comment] = ACTIONS(134),
  },
  [STATE(24)] = {
    [sym_name] = ACTIONS(132),
    [anon_sym_is] = ACTIONS(132),
    [anon_sym_has] = ACTIONS(132),
    [anon_sym_does] = ACTIONS(132),
    [anon_sym_must] = ACTIONS(132),
    [anon_sym_be] = ACTIONS(132),
    [anon_sym_do] = ACTIONS(132),
    [anon_sym_of] = ACTIONS(132),
    [anon_sym_at] = ACTIONS(132),
    [anon_sym_as] = ACTIONS(132),
    [anon_sym_by] = ACTIONS(132),
    [anon_sym_with] = ACTIONS(132),
    [anon_sym_for] = ACTIONS(132),
    [anon_sym_from] = ACTIONS(132),
    [anon_sym_to] = ACTIONS(132),
    [anon_sym_upto] = ACTIONS(132),
    [anon_sym_downto] = ACTIONS(132),
    [anon_sym_in] = ACTIONS(132),
    [anon_sym_out] = ACTIONS(132),
    [anon_sym_into] = ACTIONS(132),
    [anon_sym_outof] = ACTIONS(132),
    [anon_sym_on] = ACTIONS(132),
    [anon_sym_off] = ACTIONS(132),
    [anon_sym_AMP] = ACTIONS(130),
    [anon_sym_STAR] = ACTIONS(130),
    [anon_sym_DQUOTE] = ACTIONS(130),
    [aux_sym_string_block_token1] = ACTIONS(130),
    [anon_sym_RPAREN] = ACTIONS(130),
    [sym_punctuation] = ACTIONS(132),
    [sym_comment] = ACTIONS(130),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    ACTIONS(140), 1,
      aux_sym_string_token1,
    ACTIONS(142), 1,
      aux_sym_string_token2,
    ACTIONS(144), 1,
      anon_sym_BSLASH_LPAREN,
    STATE(26), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [17] = 5,
    ACTIONS(144), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(146), 1,
      anon_sym_DQUOTE,
    ACTIONS(148), 1,
      aux_sym_string_token1,
    ACTIONS(150), 1,
      aux_sym_string_token2,
    STATE(27), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [34] = 5,
    ACTIONS(152), 1,
      anon_sym_DQUOTE,
    ACTIONS(154), 1,
      aux_sym_string_token1,
    ACTIONS(157), 1,
      aux_sym_string_token2,
    ACTIONS(160), 1,
      anon_sym_BSLASH_LPAREN,
    STATE(27), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [51] = 5,
    ACTIONS(144), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(163), 1,
      anon_sym_DQUOTE,
    ACTIONS(165), 1,
      aux_sym_string_token1,
    ACTIONS(167), 1,
      aux_sym_string_token2,
    STATE(29), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [68] = 5,
    ACTIONS(144), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(148), 1,
      aux_sym_string_token1,
    ACTIONS(150), 1,
      aux_sym_string_token2,
    ACTIONS(169), 1,
      anon_sym_DQUOTE,
    STATE(27), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [85] = 2,
    ACTIONS(173), 1,
      aux_sym_string_token1,
    ACTIONS(171), 3,
      anon_sym_DQUOTE,
      aux_sym_string_token2,
      anon_sym_BSLASH_LPAREN,
  [94] = 2,
    ACTIONS(177), 1,
      aux_sym_string_token1,
    ACTIONS(175), 3,
      anon_sym_DQUOTE,
      aux_sym_string_token2,
      anon_sym_BSLASH_LPAREN,
  [103] = 3,
    ACTIONS(179), 1,
      aux_sym_string_block_token1,
    ACTIONS(181), 1,
      anon_sym_DASH_DASH,
    STATE(33), 1,
      aux_sym_string_block_repeat1,
  [113] = 3,
    ACTIONS(183), 1,
      aux_sym_string_block_token1,
    ACTIONS(186), 1,
      anon_sym_DASH_DASH,
    STATE(33), 1,
      aux_sym_string_block_repeat1,
  [123] = 3,
    ACTIONS(179), 1,
      aux_sym_string_block_token1,
    ACTIONS(188), 1,
      anon_sym_DASH_DASH,
    STATE(33), 1,
      aux_sym_string_block_repeat1,
  [133] = 1,
    ACTIONS(190), 1,
      aux_sym_out_dependency_token1,
  [137] = 1,
    ACTIONS(192), 1,
      aux_sym_out_dependency_token1,
  [141] = 1,
    ACTIONS(194), 1,
      aux_sym_out_dependency_token1,
  [145] = 1,
    ACTIONS(196), 1,
      ts_builtin_sym_end,
  [149] = 1,
    ACTIONS(198), 1,
      aux_sym_out_dependency_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(25)] = 0,
  [SMALL_STATE(26)] = 17,
  [SMALL_STATE(27)] = 34,
  [SMALL_STATE(28)] = 51,
  [SMALL_STATE(29)] = 68,
  [SMALL_STATE(30)] = 85,
  [SMALL_STATE(31)] = 94,
  [SMALL_STATE(32)] = 103,
  [SMALL_STATE(33)] = 113,
  [SMALL_STATE(34)] = 123,
  [SMALL_STATE(35)] = 133,
  [SMALL_STATE(36)] = 137,
  [SMALL_STATE(37)] = 141,
  [SMALL_STATE(38)] = 145,
  [SMALL_STATE(39)] = 149,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__anything, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__anything, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, 0, 1),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2, 0, 1),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_multi, 2, 0, 1),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_multi, 2, 0, 1),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_out_dependency, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_out_dependency, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_implicit_dependency, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_implicit_dependency, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_block, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_block, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [157] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [160] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 2, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_block_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_block_repeat1, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [196] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_plo(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_name,
    .primary_state_ids = ts_primary_state_ids,
    .name = "plo",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
