/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 26
#define LARGE_STATE_COUNT 19
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_name = 1,
  anon_sym_is = 2,
  anon_sym_has = 3,
  anon_sym_does = 4,
  anon_sym_must = 5,
  anon_sym_be = 6,
  anon_sym_do = 7,
  anon_sym_of = 8,
  anon_sym_at = 9,
  anon_sym_as = 10,
  anon_sym_by = 11,
  anon_sym_on = 12,
  anon_sym_off = 13,
  anon_sym_from = 14,
  anon_sym_to = 15,
  anon_sym_upto = 16,
  anon_sym_downto = 17,
  anon_sym_in = 18,
  anon_sym_out = 19,
  anon_sym_into = 20,
  anon_sym_outof = 21,
  anon_sym_DQUOTE = 22,
  aux_sym_string_token1 = 23,
  aux_sym_string_token2 = 24,
  anon_sym_BSLASH_LPAREN = 25,
  anon_sym_RPAREN = 26,
  anon_sym_LPAREN = 27,
  anon_sym_COLON = 28,
  sym_punctuation = 29,
  sym_comment = 30,
  sym_source_file = 31,
  sym__anything = 32,
  sym_keyword = 33,
  sym_string = 34,
  sym_interpolation = 35,
  sym_call = 36,
  sym_call_multi = 37,
  aux_sym_source_file_repeat1 = 38,
  aux_sym_string_repeat1 = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_name] = "name",
  [anon_sym_is] = "is",
  [anon_sym_has] = "has",
  [anon_sym_does] = "does",
  [anon_sym_must] = "must",
  [anon_sym_be] = "be",
  [anon_sym_do] = "do",
  [anon_sym_of] = "of",
  [anon_sym_at] = "at",
  [anon_sym_as] = "as",
  [anon_sym_by] = "by",
  [anon_sym_on] = "on",
  [anon_sym_off] = "off",
  [anon_sym_from] = "from",
  [anon_sym_to] = "to",
  [anon_sym_upto] = "upto",
  [anon_sym_downto] = "downto",
  [anon_sym_in] = "in",
  [anon_sym_out] = "out",
  [anon_sym_into] = "into",
  [anon_sym_outof] = "outof",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [anon_sym_BSLASH_LPAREN] = "\\(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COLON] = ":",
  [sym_punctuation] = "punctuation",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__anything] = "_anything",
  [sym_keyword] = "keyword",
  [sym_string] = "string",
  [sym_interpolation] = "interpolation",
  [sym_call] = "call",
  [sym_call_multi] = "call_multi",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_name] = sym_name,
  [anon_sym_is] = anon_sym_is,
  [anon_sym_has] = anon_sym_has,
  [anon_sym_does] = anon_sym_does,
  [anon_sym_must] = anon_sym_must,
  [anon_sym_be] = anon_sym_be,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_of] = anon_sym_of,
  [anon_sym_at] = anon_sym_at,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_by] = anon_sym_by,
  [anon_sym_on] = anon_sym_on,
  [anon_sym_off] = anon_sym_off,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_to] = anon_sym_to,
  [anon_sym_upto] = anon_sym_upto,
  [anon_sym_downto] = anon_sym_downto,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_out] = anon_sym_out,
  [anon_sym_into] = anon_sym_into,
  [anon_sym_outof] = anon_sym_outof,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [anon_sym_BSLASH_LPAREN] = anon_sym_BSLASH_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_punctuation] = sym_punctuation,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__anything] = sym__anything,
  [sym_keyword] = sym_keyword,
  [sym_string] = sym_string,
  [sym_interpolation] = sym_interpolation,
  [sym_call] = sym_call,
  [sym_call_multi] = sym_call_multi,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_is] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_has] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_does] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_must] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_be] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_of] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_at] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_by] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_on] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_off] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_to] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_upto] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_downto] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_out] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_into] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_outof] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__anything] = {
    .visible = false,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_call_multi] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_func = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_func] = "func",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_func, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 3,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 12,
  [14] = 11,
  [15] = 15,
  [16] = 9,
  [17] = 10,
  [18] = 15,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 19,
  [23] = 20,
  [24] = 24,
  [25] = 25,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '"', 10,
        '(', 16,
        ')', 15,
        ':', 17,
        '\\', 3,
        '`', 19,
        ',', 18,
        '.', 18,
        '/', 18,
        ';', 18,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '"') ADVANCE(10);
      if (lookahead == '\\') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(10);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == '`') ADVANCE(19);
      if (lookahead == '(' ||
          lookahead == ',' ||
          lookahead == '.' ||
          lookahead == '/' ||
          lookahead == ':' ||
          lookahead == ';') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(14);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 5:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '"', 10,
        '(', 16,
        ':', 17,
        '`', 19,
        ')', 18,
        ',', 18,
        '.', 18,
        '/', 18,
        ';', 18,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 6:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '"', 10,
        ')', 15,
        '\\', 3,
        '`', 19,
        '(', 18,
        ',', 18,
        '.', 18,
        '/', 18,
        ':', 18,
        ';', 18,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == '"') ADVANCE(10);
      if (lookahead == '`') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead == '(' ||
          lookahead == ')' ||
          lookahead == ',' ||
          lookahead == '.' ||
          lookahead == '/' ||
          lookahead == ':' ||
          lookahead == ';') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(12);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_BSLASH_LPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_punctuation);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'd', 3,
        'f', 4,
        'h', 5,
        'i', 6,
        'm', 7,
        'o', 8,
        't', 9,
        'u', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 's') ADVANCE(11);
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(13);
      if (lookahead == 'y') ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(18);
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == 'f') ADVANCE(21);
      if (lookahead == 'n') ADVANCE(22);
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 10:
      if (lookahead == 'p') ADVANCE(25);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_at);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_be);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_by);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_do);
      if (lookahead == 'e') ADVANCE(26);
      if (lookahead == 'w') ADVANCE(27);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 's') ADVANCE(29);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_is);
      END_STATE();
    case 20:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_of);
      if (lookahead == 'f') ADVANCE(32);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_on);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_to);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(35);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 28:
      if (lookahead == 'm') ADVANCE(37);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_has);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(38);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_off);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_out);
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 34:
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_does);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_into);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_must);
      END_STATE();
    case 40:
      if (lookahead == 'f') ADVANCE(43);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_upto);
      END_STATE();
    case 42:
      if (lookahead == 'o') ADVANCE(44);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_outof);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_downto);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [anon_sym_is] = ACTIONS(1),
    [anon_sym_has] = ACTIONS(1),
    [anon_sym_does] = ACTIONS(1),
    [anon_sym_must] = ACTIONS(1),
    [anon_sym_be] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_of] = ACTIONS(1),
    [anon_sym_at] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_by] = ACTIONS(1),
    [anon_sym_on] = ACTIONS(1),
    [anon_sym_off] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_to] = ACTIONS(1),
    [anon_sym_upto] = ACTIONS(1),
    [anon_sym_downto] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_out] = ACTIONS(1),
    [anon_sym_into] = ACTIONS(1),
    [anon_sym_outof] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_punctuation] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(25),
    [sym__anything] = STATE(2),
    [sym_keyword] = STATE(2),
    [sym_string] = STATE(2),
    [sym_call] = STATE(2),
    [sym_call_multi] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_name] = ACTIONS(5),
    [anon_sym_is] = ACTIONS(7),
    [anon_sym_has] = ACTIONS(7),
    [anon_sym_does] = ACTIONS(7),
    [anon_sym_must] = ACTIONS(7),
    [anon_sym_be] = ACTIONS(7),
    [anon_sym_do] = ACTIONS(7),
    [anon_sym_of] = ACTIONS(7),
    [anon_sym_at] = ACTIONS(7),
    [anon_sym_as] = ACTIONS(7),
    [anon_sym_by] = ACTIONS(7),
    [anon_sym_on] = ACTIONS(7),
    [anon_sym_off] = ACTIONS(7),
    [anon_sym_from] = ACTIONS(7),
    [anon_sym_to] = ACTIONS(7),
    [anon_sym_upto] = ACTIONS(7),
    [anon_sym_downto] = ACTIONS(7),
    [anon_sym_in] = ACTIONS(7),
    [anon_sym_out] = ACTIONS(7),
    [anon_sym_into] = ACTIONS(7),
    [anon_sym_outof] = ACTIONS(7),
    [anon_sym_DQUOTE] = ACTIONS(9),
    [sym_punctuation] = ACTIONS(11),
    [sym_comment] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym__anything] = STATE(3),
    [sym_keyword] = STATE(3),
    [sym_string] = STATE(3),
    [sym_call] = STATE(3),
    [sym_call_multi] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_name] = ACTIONS(5),
    [anon_sym_is] = ACTIONS(7),
    [anon_sym_has] = ACTIONS(7),
    [anon_sym_does] = ACTIONS(7),
    [anon_sym_must] = ACTIONS(7),
    [anon_sym_be] = ACTIONS(7),
    [anon_sym_do] = ACTIONS(7),
    [anon_sym_of] = ACTIONS(7),
    [anon_sym_at] = ACTIONS(7),
    [anon_sym_as] = ACTIONS(7),
    [anon_sym_by] = ACTIONS(7),
    [anon_sym_on] = ACTIONS(7),
    [anon_sym_off] = ACTIONS(7),
    [anon_sym_from] = ACTIONS(7),
    [anon_sym_to] = ACTIONS(7),
    [anon_sym_upto] = ACTIONS(7),
    [anon_sym_downto] = ACTIONS(7),
    [anon_sym_in] = ACTIONS(7),
    [anon_sym_out] = ACTIONS(7),
    [anon_sym_into] = ACTIONS(7),
    [anon_sym_outof] = ACTIONS(7),
    [anon_sym_DQUOTE] = ACTIONS(9),
    [sym_punctuation] = ACTIONS(15),
    [sym_comment] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym__anything] = STATE(3),
    [sym_keyword] = STATE(3),
    [sym_string] = STATE(3),
    [sym_call] = STATE(3),
    [sym_call_multi] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_name] = ACTIONS(19),
    [anon_sym_is] = ACTIONS(22),
    [anon_sym_has] = ACTIONS(22),
    [anon_sym_does] = ACTIONS(22),
    [anon_sym_must] = ACTIONS(22),
    [anon_sym_be] = ACTIONS(22),
    [anon_sym_do] = ACTIONS(22),
    [anon_sym_of] = ACTIONS(22),
    [anon_sym_at] = ACTIONS(22),
    [anon_sym_as] = ACTIONS(22),
    [anon_sym_by] = ACTIONS(22),
    [anon_sym_on] = ACTIONS(22),
    [anon_sym_off] = ACTIONS(22),
    [anon_sym_from] = ACTIONS(22),
    [anon_sym_to] = ACTIONS(22),
    [anon_sym_upto] = ACTIONS(22),
    [anon_sym_downto] = ACTIONS(22),
    [anon_sym_in] = ACTIONS(22),
    [anon_sym_out] = ACTIONS(22),
    [anon_sym_into] = ACTIONS(22),
    [anon_sym_outof] = ACTIONS(22),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_punctuation] = ACTIONS(28),
    [sym_comment] = ACTIONS(28),
  },
  [STATE(4)] = {
    [sym__anything] = STATE(5),
    [sym_keyword] = STATE(5),
    [sym_string] = STATE(5),
    [sym_call] = STATE(5),
    [sym_call_multi] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_name] = ACTIONS(31),
    [anon_sym_is] = ACTIONS(33),
    [anon_sym_has] = ACTIONS(33),
    [anon_sym_does] = ACTIONS(33),
    [anon_sym_must] = ACTIONS(33),
    [anon_sym_be] = ACTIONS(33),
    [anon_sym_do] = ACTIONS(33),
    [anon_sym_of] = ACTIONS(33),
    [anon_sym_at] = ACTIONS(33),
    [anon_sym_as] = ACTIONS(33),
    [anon_sym_by] = ACTIONS(33),
    [anon_sym_on] = ACTIONS(33),
    [anon_sym_off] = ACTIONS(33),
    [anon_sym_from] = ACTIONS(33),
    [anon_sym_to] = ACTIONS(33),
    [anon_sym_upto] = ACTIONS(33),
    [anon_sym_downto] = ACTIONS(33),
    [anon_sym_in] = ACTIONS(33),
    [anon_sym_out] = ACTIONS(33),
    [anon_sym_into] = ACTIONS(33),
    [anon_sym_outof] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_RPAREN] = ACTIONS(37),
    [sym_punctuation] = ACTIONS(39),
    [sym_comment] = ACTIONS(41),
  },
  [STATE(5)] = {
    [sym__anything] = STATE(5),
    [sym_keyword] = STATE(5),
    [sym_string] = STATE(5),
    [sym_call] = STATE(5),
    [sym_call_multi] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_name] = ACTIONS(43),
    [anon_sym_is] = ACTIONS(46),
    [anon_sym_has] = ACTIONS(46),
    [anon_sym_does] = ACTIONS(46),
    [anon_sym_must] = ACTIONS(46),
    [anon_sym_be] = ACTIONS(46),
    [anon_sym_do] = ACTIONS(46),
    [anon_sym_of] = ACTIONS(46),
    [anon_sym_at] = ACTIONS(46),
    [anon_sym_as] = ACTIONS(46),
    [anon_sym_by] = ACTIONS(46),
    [anon_sym_on] = ACTIONS(46),
    [anon_sym_off] = ACTIONS(46),
    [anon_sym_from] = ACTIONS(46),
    [anon_sym_to] = ACTIONS(46),
    [anon_sym_upto] = ACTIONS(46),
    [anon_sym_downto] = ACTIONS(46),
    [anon_sym_in] = ACTIONS(46),
    [anon_sym_out] = ACTIONS(46),
    [anon_sym_into] = ACTIONS(46),
    [anon_sym_outof] = ACTIONS(46),
    [anon_sym_DQUOTE] = ACTIONS(49),
    [anon_sym_RPAREN] = ACTIONS(17),
    [sym_punctuation] = ACTIONS(52),
    [sym_comment] = ACTIONS(55),
  },
  [STATE(6)] = {
    [sym__anything] = STATE(4),
    [sym_keyword] = STATE(4),
    [sym_string] = STATE(4),
    [sym_call] = STATE(4),
    [sym_call_multi] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [sym_name] = ACTIONS(31),
    [anon_sym_is] = ACTIONS(33),
    [anon_sym_has] = ACTIONS(33),
    [anon_sym_does] = ACTIONS(33),
    [anon_sym_must] = ACTIONS(33),
    [anon_sym_be] = ACTIONS(33),
    [anon_sym_do] = ACTIONS(33),
    [anon_sym_of] = ACTIONS(33),
    [anon_sym_at] = ACTIONS(33),
    [anon_sym_as] = ACTIONS(33),
    [anon_sym_by] = ACTIONS(33),
    [anon_sym_on] = ACTIONS(33),
    [anon_sym_off] = ACTIONS(33),
    [anon_sym_from] = ACTIONS(33),
    [anon_sym_to] = ACTIONS(33),
    [anon_sym_upto] = ACTIONS(33),
    [anon_sym_downto] = ACTIONS(33),
    [anon_sym_in] = ACTIONS(33),
    [anon_sym_out] = ACTIONS(33),
    [anon_sym_into] = ACTIONS(33),
    [anon_sym_outof] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [sym_punctuation] = ACTIONS(58),
    [sym_comment] = ACTIONS(58),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(60),
    [sym_name] = ACTIONS(62),
    [anon_sym_is] = ACTIONS(62),
    [anon_sym_has] = ACTIONS(62),
    [anon_sym_does] = ACTIONS(62),
    [anon_sym_must] = ACTIONS(62),
    [anon_sym_be] = ACTIONS(62),
    [anon_sym_do] = ACTIONS(62),
    [anon_sym_of] = ACTIONS(62),
    [anon_sym_at] = ACTIONS(62),
    [anon_sym_as] = ACTIONS(62),
    [anon_sym_by] = ACTIONS(62),
    [anon_sym_on] = ACTIONS(62),
    [anon_sym_off] = ACTIONS(62),
    [anon_sym_from] = ACTIONS(62),
    [anon_sym_to] = ACTIONS(62),
    [anon_sym_upto] = ACTIONS(62),
    [anon_sym_downto] = ACTIONS(62),
    [anon_sym_in] = ACTIONS(62),
    [anon_sym_out] = ACTIONS(62),
    [anon_sym_into] = ACTIONS(62),
    [anon_sym_outof] = ACTIONS(62),
    [anon_sym_DQUOTE] = ACTIONS(60),
    [anon_sym_LPAREN] = ACTIONS(64),
    [anon_sym_COLON] = ACTIONS(66),
    [sym_punctuation] = ACTIONS(62),
    [sym_comment] = ACTIONS(60),
  },
  [STATE(8)] = {
    [sym_name] = ACTIONS(62),
    [anon_sym_is] = ACTIONS(62),
    [anon_sym_has] = ACTIONS(62),
    [anon_sym_does] = ACTIONS(62),
    [anon_sym_must] = ACTIONS(62),
    [anon_sym_be] = ACTIONS(62),
    [anon_sym_do] = ACTIONS(62),
    [anon_sym_of] = ACTIONS(62),
    [anon_sym_at] = ACTIONS(62),
    [anon_sym_as] = ACTIONS(62),
    [anon_sym_by] = ACTIONS(62),
    [anon_sym_on] = ACTIONS(62),
    [anon_sym_off] = ACTIONS(62),
    [anon_sym_from] = ACTIONS(62),
    [anon_sym_to] = ACTIONS(62),
    [anon_sym_upto] = ACTIONS(62),
    [anon_sym_downto] = ACTIONS(62),
    [anon_sym_in] = ACTIONS(62),
    [anon_sym_out] = ACTIONS(62),
    [anon_sym_into] = ACTIONS(62),
    [anon_sym_outof] = ACTIONS(62),
    [anon_sym_DQUOTE] = ACTIONS(60),
    [anon_sym_RPAREN] = ACTIONS(60),
    [anon_sym_LPAREN] = ACTIONS(68),
    [anon_sym_COLON] = ACTIONS(70),
    [sym_punctuation] = ACTIONS(62),
    [sym_comment] = ACTIONS(60),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(72),
    [sym_name] = ACTIONS(74),
    [anon_sym_is] = ACTIONS(74),
    [anon_sym_has] = ACTIONS(74),
    [anon_sym_does] = ACTIONS(74),
    [anon_sym_must] = ACTIONS(74),
    [anon_sym_be] = ACTIONS(74),
    [anon_sym_do] = ACTIONS(74),
    [anon_sym_of] = ACTIONS(74),
    [anon_sym_at] = ACTIONS(74),
    [anon_sym_as] = ACTIONS(74),
    [anon_sym_by] = ACTIONS(74),
    [anon_sym_on] = ACTIONS(74),
    [anon_sym_off] = ACTIONS(74),
    [anon_sym_from] = ACTIONS(74),
    [anon_sym_to] = ACTIONS(74),
    [anon_sym_upto] = ACTIONS(74),
    [anon_sym_downto] = ACTIONS(74),
    [anon_sym_in] = ACTIONS(74),
    [anon_sym_out] = ACTIONS(74),
    [anon_sym_into] = ACTIONS(74),
    [anon_sym_outof] = ACTIONS(74),
    [anon_sym_DQUOTE] = ACTIONS(72),
    [sym_punctuation] = ACTIONS(72),
    [sym_comment] = ACTIONS(72),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(76),
    [sym_name] = ACTIONS(78),
    [anon_sym_is] = ACTIONS(78),
    [anon_sym_has] = ACTIONS(78),
    [anon_sym_does] = ACTIONS(78),
    [anon_sym_must] = ACTIONS(78),
    [anon_sym_be] = ACTIONS(78),
    [anon_sym_do] = ACTIONS(78),
    [anon_sym_of] = ACTIONS(78),
    [anon_sym_at] = ACTIONS(78),
    [anon_sym_as] = ACTIONS(78),
    [anon_sym_by] = ACTIONS(78),
    [anon_sym_on] = ACTIONS(78),
    [anon_sym_off] = ACTIONS(78),
    [anon_sym_from] = ACTIONS(78),
    [anon_sym_to] = ACTIONS(78),
    [anon_sym_upto] = ACTIONS(78),
    [anon_sym_downto] = ACTIONS(78),
    [anon_sym_in] = ACTIONS(78),
    [anon_sym_out] = ACTIONS(78),
    [anon_sym_into] = ACTIONS(78),
    [anon_sym_outof] = ACTIONS(78),
    [anon_sym_DQUOTE] = ACTIONS(76),
    [sym_punctuation] = ACTIONS(76),
    [sym_comment] = ACTIONS(76),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(80),
    [sym_name] = ACTIONS(82),
    [anon_sym_is] = ACTIONS(82),
    [anon_sym_has] = ACTIONS(82),
    [anon_sym_does] = ACTIONS(82),
    [anon_sym_must] = ACTIONS(82),
    [anon_sym_be] = ACTIONS(82),
    [anon_sym_do] = ACTIONS(82),
    [anon_sym_of] = ACTIONS(82),
    [anon_sym_at] = ACTIONS(82),
    [anon_sym_as] = ACTIONS(82),
    [anon_sym_by] = ACTIONS(82),
    [anon_sym_on] = ACTIONS(82),
    [anon_sym_off] = ACTIONS(82),
    [anon_sym_from] = ACTIONS(82),
    [anon_sym_to] = ACTIONS(82),
    [anon_sym_upto] = ACTIONS(82),
    [anon_sym_downto] = ACTIONS(82),
    [anon_sym_in] = ACTIONS(82),
    [anon_sym_out] = ACTIONS(82),
    [anon_sym_into] = ACTIONS(82),
    [anon_sym_outof] = ACTIONS(82),
    [anon_sym_DQUOTE] = ACTIONS(80),
    [sym_punctuation] = ACTIONS(80),
    [sym_comment] = ACTIONS(80),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(84),
    [sym_name] = ACTIONS(86),
    [anon_sym_is] = ACTIONS(86),
    [anon_sym_has] = ACTIONS(86),
    [anon_sym_does] = ACTIONS(86),
    [anon_sym_must] = ACTIONS(86),
    [anon_sym_be] = ACTIONS(86),
    [anon_sym_do] = ACTIONS(86),
    [anon_sym_of] = ACTIONS(86),
    [anon_sym_at] = ACTIONS(86),
    [anon_sym_as] = ACTIONS(86),
    [anon_sym_by] = ACTIONS(86),
    [anon_sym_on] = ACTIONS(86),
    [anon_sym_off] = ACTIONS(86),
    [anon_sym_from] = ACTIONS(86),
    [anon_sym_to] = ACTIONS(86),
    [anon_sym_upto] = ACTIONS(86),
    [anon_sym_downto] = ACTIONS(86),
    [anon_sym_in] = ACTIONS(86),
    [anon_sym_out] = ACTIONS(86),
    [anon_sym_into] = ACTIONS(86),
    [anon_sym_outof] = ACTIONS(86),
    [anon_sym_DQUOTE] = ACTIONS(84),
    [sym_punctuation] = ACTIONS(84),
    [sym_comment] = ACTIONS(84),
  },
  [STATE(13)] = {
    [sym_name] = ACTIONS(86),
    [anon_sym_is] = ACTIONS(86),
    [anon_sym_has] = ACTIONS(86),
    [anon_sym_does] = ACTIONS(86),
    [anon_sym_must] = ACTIONS(86),
    [anon_sym_be] = ACTIONS(86),
    [anon_sym_do] = ACTIONS(86),
    [anon_sym_of] = ACTIONS(86),
    [anon_sym_at] = ACTIONS(86),
    [anon_sym_as] = ACTIONS(86),
    [anon_sym_by] = ACTIONS(86),
    [anon_sym_on] = ACTIONS(86),
    [anon_sym_off] = ACTIONS(86),
    [anon_sym_from] = ACTIONS(86),
    [anon_sym_to] = ACTIONS(86),
    [anon_sym_upto] = ACTIONS(86),
    [anon_sym_downto] = ACTIONS(86),
    [anon_sym_in] = ACTIONS(86),
    [anon_sym_out] = ACTIONS(86),
    [anon_sym_into] = ACTIONS(86),
    [anon_sym_outof] = ACTIONS(86),
    [anon_sym_DQUOTE] = ACTIONS(84),
    [anon_sym_RPAREN] = ACTIONS(84),
    [sym_punctuation] = ACTIONS(86),
    [sym_comment] = ACTIONS(84),
  },
  [STATE(14)] = {
    [sym_name] = ACTIONS(82),
    [anon_sym_is] = ACTIONS(82),
    [anon_sym_has] = ACTIONS(82),
    [anon_sym_does] = ACTIONS(82),
    [anon_sym_must] = ACTIONS(82),
    [anon_sym_be] = ACTIONS(82),
    [anon_sym_do] = ACTIONS(82),
    [anon_sym_of] = ACTIONS(82),
    [anon_sym_at] = ACTIONS(82),
    [anon_sym_as] = ACTIONS(82),
    [anon_sym_by] = ACTIONS(82),
    [anon_sym_on] = ACTIONS(82),
    [anon_sym_off] = ACTIONS(82),
    [anon_sym_from] = ACTIONS(82),
    [anon_sym_to] = ACTIONS(82),
    [anon_sym_upto] = ACTIONS(82),
    [anon_sym_downto] = ACTIONS(82),
    [anon_sym_in] = ACTIONS(82),
    [anon_sym_out] = ACTIONS(82),
    [anon_sym_into] = ACTIONS(82),
    [anon_sym_outof] = ACTIONS(82),
    [anon_sym_DQUOTE] = ACTIONS(80),
    [anon_sym_RPAREN] = ACTIONS(80),
    [sym_punctuation] = ACTIONS(82),
    [sym_comment] = ACTIONS(80),
  },
  [STATE(15)] = {
    [ts_builtin_sym_end] = ACTIONS(88),
    [sym_name] = ACTIONS(90),
    [anon_sym_is] = ACTIONS(90),
    [anon_sym_has] = ACTIONS(90),
    [anon_sym_does] = ACTIONS(90),
    [anon_sym_must] = ACTIONS(90),
    [anon_sym_be] = ACTIONS(90),
    [anon_sym_do] = ACTIONS(90),
    [anon_sym_of] = ACTIONS(90),
    [anon_sym_at] = ACTIONS(90),
    [anon_sym_as] = ACTIONS(90),
    [anon_sym_by] = ACTIONS(90),
    [anon_sym_on] = ACTIONS(90),
    [anon_sym_off] = ACTIONS(90),
    [anon_sym_from] = ACTIONS(90),
    [anon_sym_to] = ACTIONS(90),
    [anon_sym_upto] = ACTIONS(90),
    [anon_sym_downto] = ACTIONS(90),
    [anon_sym_in] = ACTIONS(90),
    [anon_sym_out] = ACTIONS(90),
    [anon_sym_into] = ACTIONS(90),
    [anon_sym_outof] = ACTIONS(90),
    [anon_sym_DQUOTE] = ACTIONS(88),
    [sym_punctuation] = ACTIONS(88),
    [sym_comment] = ACTIONS(88),
  },
  [STATE(16)] = {
    [sym_name] = ACTIONS(74),
    [anon_sym_is] = ACTIONS(74),
    [anon_sym_has] = ACTIONS(74),
    [anon_sym_does] = ACTIONS(74),
    [anon_sym_must] = ACTIONS(74),
    [anon_sym_be] = ACTIONS(74),
    [anon_sym_do] = ACTIONS(74),
    [anon_sym_of] = ACTIONS(74),
    [anon_sym_at] = ACTIONS(74),
    [anon_sym_as] = ACTIONS(74),
    [anon_sym_by] = ACTIONS(74),
    [anon_sym_on] = ACTIONS(74),
    [anon_sym_off] = ACTIONS(74),
    [anon_sym_from] = ACTIONS(74),
    [anon_sym_to] = ACTIONS(74),
    [anon_sym_upto] = ACTIONS(74),
    [anon_sym_downto] = ACTIONS(74),
    [anon_sym_in] = ACTIONS(74),
    [anon_sym_out] = ACTIONS(74),
    [anon_sym_into] = ACTIONS(74),
    [anon_sym_outof] = ACTIONS(74),
    [anon_sym_DQUOTE] = ACTIONS(72),
    [anon_sym_RPAREN] = ACTIONS(72),
    [sym_punctuation] = ACTIONS(74),
    [sym_comment] = ACTIONS(72),
  },
  [STATE(17)] = {
    [sym_name] = ACTIONS(78),
    [anon_sym_is] = ACTIONS(78),
    [anon_sym_has] = ACTIONS(78),
    [anon_sym_does] = ACTIONS(78),
    [anon_sym_must] = ACTIONS(78),
    [anon_sym_be] = ACTIONS(78),
    [anon_sym_do] = ACTIONS(78),
    [anon_sym_of] = ACTIONS(78),
    [anon_sym_at] = ACTIONS(78),
    [anon_sym_as] = ACTIONS(78),
    [anon_sym_by] = ACTIONS(78),
    [anon_sym_on] = ACTIONS(78),
    [anon_sym_off] = ACTIONS(78),
    [anon_sym_from] = ACTIONS(78),
    [anon_sym_to] = ACTIONS(78),
    [anon_sym_upto] = ACTIONS(78),
    [anon_sym_downto] = ACTIONS(78),
    [anon_sym_in] = ACTIONS(78),
    [anon_sym_out] = ACTIONS(78),
    [anon_sym_into] = ACTIONS(78),
    [anon_sym_outof] = ACTIONS(78),
    [anon_sym_DQUOTE] = ACTIONS(76),
    [anon_sym_RPAREN] = ACTIONS(76),
    [sym_punctuation] = ACTIONS(78),
    [sym_comment] = ACTIONS(76),
  },
  [STATE(18)] = {
    [sym_name] = ACTIONS(90),
    [anon_sym_is] = ACTIONS(90),
    [anon_sym_has] = ACTIONS(90),
    [anon_sym_does] = ACTIONS(90),
    [anon_sym_must] = ACTIONS(90),
    [anon_sym_be] = ACTIONS(90),
    [anon_sym_do] = ACTIONS(90),
    [anon_sym_of] = ACTIONS(90),
    [anon_sym_at] = ACTIONS(90),
    [anon_sym_as] = ACTIONS(90),
    [anon_sym_by] = ACTIONS(90),
    [anon_sym_on] = ACTIONS(90),
    [anon_sym_off] = ACTIONS(90),
    [anon_sym_from] = ACTIONS(90),
    [anon_sym_to] = ACTIONS(90),
    [anon_sym_upto] = ACTIONS(90),
    [anon_sym_downto] = ACTIONS(90),
    [anon_sym_in] = ACTIONS(90),
    [anon_sym_out] = ACTIONS(90),
    [anon_sym_into] = ACTIONS(90),
    [anon_sym_outof] = ACTIONS(90),
    [anon_sym_DQUOTE] = ACTIONS(88),
    [anon_sym_RPAREN] = ACTIONS(88),
    [sym_punctuation] = ACTIONS(90),
    [sym_comment] = ACTIONS(88),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(92), 1,
      anon_sym_DQUOTE,
    ACTIONS(94), 1,
      aux_sym_string_token1,
    ACTIONS(96), 1,
      aux_sym_string_token2,
    ACTIONS(98), 1,
      anon_sym_BSLASH_LPAREN,
    STATE(21), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [17] = 5,
    ACTIONS(98), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(100), 1,
      anon_sym_DQUOTE,
    ACTIONS(102), 1,
      aux_sym_string_token1,
    ACTIONS(104), 1,
      aux_sym_string_token2,
    STATE(19), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [34] = 5,
    ACTIONS(106), 1,
      anon_sym_DQUOTE,
    ACTIONS(108), 1,
      aux_sym_string_token1,
    ACTIONS(111), 1,
      aux_sym_string_token2,
    ACTIONS(114), 1,
      anon_sym_BSLASH_LPAREN,
    STATE(21), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [51] = 5,
    ACTIONS(94), 1,
      aux_sym_string_token1,
    ACTIONS(96), 1,
      aux_sym_string_token2,
    ACTIONS(98), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(117), 1,
      anon_sym_DQUOTE,
    STATE(21), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [68] = 5,
    ACTIONS(98), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(119), 1,
      anon_sym_DQUOTE,
    ACTIONS(121), 1,
      aux_sym_string_token1,
    ACTIONS(123), 1,
      aux_sym_string_token2,
    STATE(22), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [85] = 2,
    ACTIONS(127), 1,
      aux_sym_string_token1,
    ACTIONS(125), 3,
      anon_sym_DQUOTE,
      aux_sym_string_token2,
      anon_sym_BSLASH_LPAREN,
  [94] = 1,
    ACTIONS(129), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(19)] = 0,
  [SMALL_STATE(20)] = 17,
  [SMALL_STATE(21)] = 34,
  [SMALL_STATE(22)] = 51,
  [SMALL_STATE(23)] = 68,
  [SMALL_STATE(24)] = 85,
  [SMALL_STATE(25)] = 94,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__anything, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__anything, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, 0, 1),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2, 0, 1),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_multi, 2, 0, 1),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_multi, 2, 0, 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [108] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [111] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [114] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_plo(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_name,
    .primary_state_ids = ts_primary_state_ids,
    .name = "plo",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
